"""add event timetable and awards

Revision ID: 353d4d3369d1
Revises: 559409548ece
Create Date: 2026-07-22 22:01:43.732328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353d4d3369d1'
down_revision: Union[str, Sequence[str], None] = '559409548ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nuestar_event_awards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['nuestar_event_entries.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['nuestar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nuestar_event_entries', sa.Column('presenters', sa.String(), nullable=True))
    op.add_column('nuestar_event_entries', sa.Column('talk_seconds', sa.Integer(), server_default='180', nullable=False))
    op.add_column('nuestar_event_entries', sa.Column('qa_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('nuestar_event_entries', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('nuestar_event_entries', sa.Column('scheduled_at', sa.String(), nullable=True))
    op.add_column('nuestar_events', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('nuestar_events', sa.Column('buffer_seconds', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nuestar_events', 'buffer_seconds')
    op.drop_column('nuestar_events', 'start_time')
    op.drop_column('nuestar_event_entries', 'scheduled_at')
    op.drop_column('nuestar_event_entries', 'order_index')
    op.drop_column('nuestar_event_entries', 'qa_seconds')
    op.drop_column('nuestar_event_entries', 'talk_seconds')
    op.drop_column('nuestar_event_entries', 'presenters')
    op.drop_table('nuestar_event_awards')
    # ### end Alembic commands ###
