"""add morning program

Revision ID: 857afa6bc10f
Revises: 353d4d3369d1
Create Date: 2026-07-30 19:45:02.609842

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857afa6bc10f'
down_revision: Union[str, Sequence[str], None] = '353d4d3369d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morning_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('task_points', sa.Integer(), nullable=False),
    sa.Column('streak_bonus_per_day', sa.Integer(), nullable=False),
    sa.Column('streak_bonus_max', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_tips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('checkin_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_morning_checkin_user_date')
    )
    op.create_table('morning_task_dones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('done_date', sa.Date(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['morning_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', 'done_date', name='uq_morning_task_done_user_task_date')
    )
    # ### end Alembic commands ###

    _seed()


def _seed() -> None:
    """初期設定・初期コンテンツを入れる（すべて管理画面から変更できる）。"""
    conn = op.get_bind()

    conn.execute(
        sa.text(
            "INSERT INTO morning_settings (id, enabled, start_minute, end_minute,"
            " base_points, task_points, streak_bonus_per_day, streak_bonus_max)"
            " VALUES (:id, 1, 360, 480, 20, 5, 2, 20)"
        ),
        {"id": str(uuid.uuid4())},
    )

    tasks = [
        ("カーテンを開けて朝日を浴びる", "起きて15分以内に光を浴びると体内時計がリセットされます。"),
        ("コップ1杯の水を飲む", "睡眠中に失った水分を戻すと頭がはっきりします。"),
        ("今日やる3つを書き出す", "多くても3つまで。優先順位が決まると迷う時間が消えます。"),
        ("いちばん重いタスクに30分だけ着手する", "朝は集中力が最も高い時間帯。難しい仕事から手をつけます。"),
        ("Discord に朝活の宣言を投稿する", "仲間に見られていると継続率が上がります。"),
        ("軽くストレッチ・散歩をする", "5分でも体を動かすと眠気が抜けます。"),
    ]
    for i, (title, description) in enumerate(tasks):
        conn.execute(
            sa.text(
                "INSERT INTO morning_tasks (id, title, description, sort_order, is_active)"
                " VALUES (:id, :title, :description, :sort_order, 1)"
            ),
            {
                "id": str(uuid.uuid4()),
                "title": title,
                "description": description,
                "sort_order": i,
            },
        )

    tips = [
        (
            "前夜に「明日の朝やること」を決めておく",
            "朝に何をするか考えるところから始めると、それだけで意志力を使ってしまいます。"
            "寝る前に机の上に必要なものを出しておくところまでやると、朝は座るだけで始められます。",
        ),
        (
            "起きる時間ではなく寝る時間を固定する",
            "早起きは睡眠時間を削ることではありません。6時に起きたいなら逆算して寝る時刻を先に決めます。",
        ),
        (
            "スマホをベッドから離して置く",
            "アラームを止めるために立ち上がる状況を作るだけで、二度寝の確率は大きく下がります。",
        ),
        (
            "最初の1週間はハードルを下げる",
            "「6時に起きてアプリを開く」だけで成功とみなします。習慣化するまでは量より連続日数です。",
        ),
        (
            "1日抜けても翌日に必ず戻る",
            "連続が途切れた翌日に戻れるかどうかがすべてです。2日続けて休むと元に戻りにくくなります。",
        ),
    ]
    for i, (title, body) in enumerate(tips):
        conn.execute(
            sa.text(
                "INSERT INTO morning_tips (id, title, body, sort_order, is_active)"
                " VALUES (:id, :title, :body, :sort_order, 1)"
            ),
            {"id": str(uuid.uuid4()), "title": title, "body": body, "sort_order": i},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morning_task_dones')
    op.drop_table('morning_checkins')
    op.drop_table('morning_tips')
    op.drop_table('morning_tasks')
    op.drop_table('morning_settings')
    # ### end Alembic commands ###
