"""add morning lucky chance and declaration post

Revision ID: a2b4568f2e79
Revises: 857afa6bc10f
Create Date: 2026-07-30 20:39:02.736190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b4568f2e79'
down_revision: Union[str, Sequence[str], None] = '857afa6bc10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# app.services.morning.DEFAULT_POST_TEMPLATE と同じ内容。
# マイグレーションはアプリのコードに依存させたくないので値を複製している。
DEFAULT_POST_TEMPLATE = """おはようございます！ {time} から朝活を始めます 🌅
今日やること:
{tasks}
（{streak}日連続の朝活 / {date}）"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morning_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_date', name='uq_morning_post_user_date')
    )
    op.add_column('login_bonuses', sa.Column('lucky_points', sa.Integer(), server_default='0', nullable=False))
    op.add_column('morning_checkins', sa.Column('lucky_points', sa.Integer(), server_default='0', nullable=False))
    op.add_column('morning_settings', sa.Column('lucky_enabled', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('morning_settings', sa.Column('lucky_min_points', sa.Integer(), server_default='10', nullable=False))
    op.add_column('morning_settings', sa.Column('lucky_max_points', sa.Integer(), server_default='30', nullable=False))
    op.add_column('morning_settings', sa.Column('post_points', sa.Integer(), server_default='10', nullable=False))
    op.add_column('morning_settings', sa.Column('post_template', sa.Text(), server_default='', nullable=False))
    op.add_column('morning_tasks', sa.Column('complete_on_post', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    _seed()


def _seed() -> None:
    """既定の定型文を入れ、Discord投稿タスクを「投稿でクリア」にする。"""
    conn = op.get_bind()

    conn.execute(
        sa.text("UPDATE morning_settings SET post_template = :tpl WHERE post_template = ''"),
        {"tpl": DEFAULT_POST_TEMPLATE},
    )
    # 初期投入した「Discord に朝活の宣言を投稿する」は投稿で自動クリアにする
    conn.execute(
        sa.text(
            "UPDATE morning_tasks SET complete_on_post = 1"
            " WHERE title LIKE '%Discord%' AND title LIKE '%投稿%'"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morning_tasks', 'complete_on_post')
    op.drop_column('morning_settings', 'post_template')
    op.drop_column('morning_settings', 'post_points')
    op.drop_column('morning_settings', 'lucky_max_points')
    op.drop_column('morning_settings', 'lucky_min_points')
    op.drop_column('morning_settings', 'lucky_enabled')
    op.drop_column('morning_checkins', 'lucky_points')
    op.drop_column('login_bonuses', 'lucky_points')
    op.drop_table('morning_posts')
    # ### end Alembic commands ###
