"""add shared bookshelf

Revision ID: d34689fa5ac5
Revises: b399d34c9c4a
Create Date: 2026-07-31 05:43:01.717647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34689fa5ac5'
down_revision: Union[str, Sequence[str], None] = 'b399d34c9c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn13', sa.String(length=13), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authors', sa.String(length=300), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=True)
    op.create_table('book_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_book_registration_user_book')
    )
    op.create_index(op.f('ix_book_registrations_book_id'), 'book_registrations', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_registrations_book_id'), table_name='book_registrations')
    op.drop_table('book_registrations')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
